### ISSUE TITLE
add pricing table for hotel room per night & add page description to api

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Meredith#8]
https://docs.google.com/spreadsheets/d/1I5hJXS6TcN6dz57rXlx5NVejMmp1x28VZP1RvoMdJgo/edit?usp=sharing

need page description as well

**Comment by StrangeWill** [comment]
- New table for pricing
  - Date
  - Price
- API changes:
  - Query per hotel ID per date (YYYY-MM-DD), return price.

**Comment by paulchrisluke** [comment]
for client demo tomorrow, I replaced content in the calltoaction and header field with a placeholder price integer and description. We can undo this once the api is built.

![image](https://user-images.githubusercontent.com/5694308/59051509-420c3600-88b7-11e9-9213-b14472755b7f.png)

**Comment by StrangeWill** [comment]
That's fine, not like we use those columns (they're more for cards... which I guess cards should be their own module to be honest).

**Comment by paulchrisluke** [comment]
Agree with cards being their own module , I'll use them next client

**Comment by paulchrisluke** [comment]
@StrangeWill whats the effort look like on this?

> * New table for pricing
>   
>   * Date
>   * Price
> * API changes:
>   
>   * Query per hotel ID per date (YYYY-MM-DD), return price.

is this possible?

**Comment by StrangeWill** [comment]
Super easy, just wanted to make sure that looked good, going to implement that right now.

**Comment by StrangeWill** [comment]
Prices added in fd92c6e7fdfbc9c8311667807509f3e38ed7a9aa

**Comment by StrangeWill** [comment]
Description added in fabd9b4618d7406a48000d5398ef9c02f8d545a1
