### ISSUE TITLE
add categories support

### ISSUE THREAD

**Issue by paulchrisluke** [whynotearth/Meredith#9]
Kirirom is going to have more categories than just accommodations. The pages will still be the same style as the listing page, just need to add category for search and home page organization purposes:

https://www.figma.com/file/ZCcD4RV58FowzVvWdVmY4a/Airbnb-Dark-mode-by-PaulChrisLuke?node-id=1%3A2

categories are:
- accommodations
- food
- events
- experiences
- blog

**Comment by StrangeWill** [comment]
Are these just categories or new modules?

**Comment by StrangeWill** [comment]
Added as bd122fb601dc9cf0fd684c2da90d4e57ce9ff488
